### ISSUE TITLE
how to capture the payload in the console.log.

### ISSUE THREAD

**Issue by praveenkumar12353** [jlyon87/sf-five9-subscriber#1]
Hi Justin!
 how can i capture the Payload information. In the parenthelper.js we are getting only the Eventid,eventReason, sessionid and state. Is there any way that we can capture the payload data as well.

@justin-lyon

**Comment by justin-lyon** [comment]
Hi Praveen, sorry I don't think I'll be able to help much. 

I haven't touched this code since I last pushed, and I don't maintain the project that uses it anymore. 

However, I can point you to this method in the aura component's helper
https://github.com/justin-lyon/sf-five9-subscriber/blob/master/force-app/main/default/aura/FiveNineSocketAPI/FiveNineSocketAPIHelper.js#L201

Here is where all the available data from five9 is mapped. If you're looking for more data, it should be there. Lastly, do speak with your five9 reps - they will have more info in their api documentation.

**Comment by praveenkumar12353** [comment]
Thanks for the response, Justin!
